== MakeHandsOn, the Student Assignment Generator

This makes up student "todo" exercise directories directly from the solutions.
The benefits include the following:

* To the instructor, a lot less work!
* To the student, the ability to *reliably* compare their work-in-progress
with the working solution.

The starting assumption is that all the files for the course are organized
into directories, one per assignment, rather like (say) an Eclipse workspace.
In particular, the working versions should be stored in folders called "xxxsolution",
e.g., "ex51solution" might be the solution version of Exercise 5.1.

This program performs various substitutions on files. It creates a copy
of each "xxxsolution" directory as "xxx" (which must not exist),
making all the line-based changes shown below.

=== Marking up the solution version of files

The following line-based changes are baked into the code:

	//- through to //+ inclusive are DELETED from the output
	
Other changes are configurable (see below). The following are currently
provided:

1) In the Solutions input folder, mark TODO lines with //T instead of TODO 
so the solution doesn't show in Tasks Window in Eclipse. 
//T (with a space after!) gets turned into // TODO in the exercise version.

2) //H  becomes // *HINT*

3) Use //R for replacement variables, that is, placeholders for stuff that gets cut
//R

4) Remove "solution" from filenames in config files (so be warned: don't
use the word 'solution' unless you mean it to go away in the non-solution.
This sounds painful but is required so that the Eclipse .project/.classpath
files will work

5) Finally, we replace absolute paths. At present the value of ${user.home} gets
turned into C:/.  If you have used any absolute paths (which you 
shouldn't), this could save your bacon
e.g., a line containing /home/ian/testdata would be changed to C:/testdata

Actually this is implemented as processing system properties as a key, 
e.g., because the default Properties file says
${user.home}=C:/
then a line like
Look in /home/ian/testdata
will come out as
Look in C:/testdata

Changes are made only to files whose extensions are listed in 
SUB_TEXT_FILE_EXTENS in the program, which currently includes
most sensible filename endings, but you might want to review it.

Note that no changes will be made in directories named CVS or .git or .metadata.

Finally, a list of files can be excluded by their full name. For example, if in an
exercise, the student is directed to create a file from scratch, that file should
obviously exist in the solution folder but not in the generated student folder.
The filename "exclude-files.txt" may exist only in the root of a starting (solution)
directory, containing one filename per line, as for example:

----
$ cat ex21solution/exclude-files.txt
EventsListerTest.java
----

In this example, the file "EventListerTest.java' is the file the student must create,
so neither it (nor, of course, the file ignore-files.txt) will be copied to the ex21 folder.

=== Customizing

The text substitutions are loaded from a properties file to be easy to change, but
if you do the documentation above will not strictly apply!

The input format is: regex=replacement.  If you do need to change it,
consult the included properties file to see the examples.

You can change this by editing makehandson.properties AND
re-generating the Jar file (see "Rebuilding" below). You could probably
just put the new properties file on your CLASSPATH ahead of the jar file, 
but this hasn't been tested.

=== Generating the Non_solution Versions from the Marked-up Solutions

Each folder should be named foosolution, e.g., ex41solution. This will create ex41.

Then run "java -jar makehandson.jar *solution" in the crsXXX
directory. This will create ex11 from ex11solution, and so on.

=== Rebuilding the Program

The source file for makehandson is an Eclipse project. Open it in Eclipse
and make any changes.

Or, using Maven 3, just do _mvn package_

=== Bugs/ToDos

Warn or remove-by-default each top-level project directory.

Generate HTML hints by diff-ing the changed files.

There ought to be a way to build several related projects from the same tree.
For example, a main solution and a bonus solution.
This is left as a post-1.0-RELEASE proposal.

=== Modifying the Program

Well, this is Github, so just fork it and hack away. If you make it better,
send me a note and a pull request.

Enjoy.

Ian Darwin
ian@darwinsys.com
