= MakeHandsOn, the Student Assignment Generator
:author: Ian Darwin
:email: https://darwinsys.com/java

This makes up student "todo" exercise directories directly from the solutions.
The ideal target is a class where students are given (or checkout from a DVCS)
a folder with exercises and their solutions, with names like

	ex11
	ex11solution
	ex21
	ex21solution

and so on (ex21 is the chapter 2 exercise #1 in this example).

Where I come from (commercial training) we let the students have access to the solutions
in case they get stuck and would rather see the code.
In some academic situations this may not be acceptable, so there is a change request for an option
to put the students' exercises into a separate folder that you can distribute.

The program's benefits include the following:

* To the instructor, more certainty, and a lot less work!
* To the student, the ability to *reliably* compare their work-in-progress
with the working solution.

The starting assumption is that all the files for the course are organized
into directories, one per assignment, rather like (say) an Eclipse workspace.
In particular, the working versions should be stored in folders called "xxsolution",
e.g., "ex51solution" might be the solution version of Exercise 5.1.

While my background is in teaching Java, and the initial users have been Java instructors,
the program is not limited to working on Java programs; it could be
used on any programming language or, indeed, on anything that is text based
(as all document files should be; see https://asciidoctor.org[AsciiDoc]).
It is _not_ intended to make changes in binary files (images, office documents, or any other non-text format),
though it will copy them unchanged into the student folders.

The program has so far been tested with Eclipse and Android Studio.
It _should_ work with any other sane IDE, but this has not been tested yet.

This program performs various substitutions on files. It creates a copy
of each "xxsolution" directory as "xx" (which must not exist),
making all the line-based changes shown below.

== Pre-requisites

This program is written in Java and thus requires a JVM.
If there's any demand I can make up an installer for Windows, Mac, Linux, which
will install a minimal JVM that the program has been tested with.
My initial target was Java course developers, so the installer hasn't
been needed up til now.


== Marking up the solution version of files

The following line-based changes are baked into the code:

=== ToDo Items

In the Solutions input folder, you can mark TODO lines with //T instead of // TODO 
so the solution doesn't show in Tasks Window in Eclipse (since you should only be editing the solutions versions,
and not filling in the student's TODOs at this stage!).

	//T (with a space after!) gets turned into // TODO in the exercise version.

=== Cut Mode

	//- through to //+ inclusive are DELETED from the output
	
The //- and //+ must each be on a line by itself; indentation is allowed but
no other characters before or after.

If //R has been given (see below), it will replace the cut lines.

=== Replacement Text for Cut Mode

Use //R for replacement variables, that is, placeholders for stuff that gets cut.
This can be useful to make the exercise code compile without errors.
This must go before the //- ... //+ section.
For example:

----
//T Compute in int variable i the value of the expression shown in the notes.
//R int i = 0;
//-
int i = Math.sqrt(jNumber) * Math.cos(kNumber);
//+
----

This will generate these two lines in the output file:

----
// TODO  Compute in int variable i the value of the expression shown in the notes.
int i = 0;
----

Thus any following code that requires _i_ will compile, though obviously not yield the correct
value until the student completes the ToDo step.

=== Comment-Out Mode

Lines of code can be left in the student version but commented out, using the C99/C++/Java/C# convention *//*.
Control this using //C+ and //C-
(these tags can be indented but each must otherwise be on a line by itself).

	//C+
	int x = 42;
	//C-

results in:

	// int x = 42;

=== Hints

	//H  becomes // *HINT*

It's easier on the eyes when editing the solution version, but makes the hint stand out in the student version.

=== Text Substitution

eXchange mode (//X) allows substitution of text with a block

----
//X+ :::text to change:::replacement text
Inside this block, any instance of "text to change" will be replaced with "replacement text" 
//X-
----

Note that it is a straight replacement and does not use regex's . Replacement starts immediately after the //X+ ... line and ends at //X-

=== Conditional Output

The program implements a small subset of the C Pre-processor to allow conditional processing.

	#if	ex42solution
	This text will only appear if we are running
	from the ex42solution directory, not from, say
	ex24solution.
	#endif

This allows linked or symlinked files, which can certainly be convenient for maintenance if done carefully.

=== Creating Output that doesn't say "solution"

We remove "solution" from filenames in most files including config files (so be warned: don't
use the word 'solution' unless you mean it to go away in the non-solution version.
It is case sensitive so you can refer to "the Solution" and have it work OK.
This sounds painful but is required so that the Eclipse .project/.classpath
files will work

=== Fixing Absolute Paths

Finally, we replace absolute paths. At present the value of the ${user.home} variable gets
turned into C:/.  If you have used any absolute paths (which you 
shouldn't), this could save your bacon
e.g., a line containing /home/ian/testdata would be changed to C:/testdata

This is implemented by looking in the system properties.
E.g., assuming the default JDK System Properties list on MS-Windows says

	${user.home}=C:/

then a line like

	Look in /home/ian/testdata

will come out in the student exercises version as

	Look in C:/testdata

=== Which Files To Process?

Changes are made only to files whose extensions are hard-coded in 
the variable _SUB_TEXT_FILE_EXTENS_ in the program, which currently includes
most sensible filename endings, but you might want to review it.

Note that no changes will be made in directories named CVS, .svn, .git, .metadata, bin or target
(see the variable _IGNORE_DIRS_ in the source code).

A list of files can be excluded by their full name. For example, if in an
exercise, the student is directed to create a file from scratch, that file should
obviously exist in the solution folder but not in the generated student folder.
The filename _exclude-files.txt_ may exist _only in the root of a starting (solution)
directory_, containing one filename per line, as for example:

----
$ cat ex21solution/exclude-files.txt
EventsListerTest.java
----

In this example, the file _EventsListerTest.java_ is the file the student must create,
so neither it (nor, of course, the file _exclude-files.txt_) will be copied to the ex21 folder.

Similarly, a list of files that must not be modified can be created in a file named __verbatim-files.txt__.
Typical uses include binary files, and files containing markup that conflicts with that of this program.

=== Customizing The Substitutions

The text substitutions are loaded from a properties file to be easy to change, but
if you do so, the documentation above will not strictly apply!

The input format is: regex=replacement.  If you do need to change it,
consult the included properties file to see the examples.

You can change this by editing makehandson.properties AND
re-generating the Jar file (see "Rebuilding" below). You could probably
just put the new properties file on your CLASSPATH ahead of the jar file, 
but this hasn't been tested.

== Running MakeHandsOn: Generating the Student Versions

After all that markup, you are ready to build the non-solution versions.
Each folder should be named foosolution, e.g., ex41solution. This will create ex41.

Then run "java -jar makehandson.jar *solution" in the crsNNN
directory. This will create ex11 from ex11solution, and so on.

There is a Unix script in the scripts folder that may work for you if you do "mvn install".

== Project Automation

This program is the first step to automating creation of your students' workspace.
The more you automate (and test), the less chance of errors creeping in!

I normally do most of my maintenance on my https://openbsd.org[Unix] laptop,
even though we normally run courses on MS-Windows.
When it's tmie for a course rev, I do the work on the laptop, test, and commit the changes.
Then I get the Lab to make up a new VM, install Java and the IDEs and other tools,
or just start with the previous load.
I just git clone or git pull a few repos, run a script, and barring the unforseen, I'm done.
No need to fight with Windows any more than the bare minimum.

The next step in automation is to have a Shell script (install git bash if on Windows) -
I called mine _all-in_ - to do the following.
Of course where I use maven, others may use gradle, make, etc.

* git clone any auxilliary repos (sample files, etc.)
* git pull in all the _solution_ folders
* run _mvn test_ in the *solution* folders - no point going further
	if the solutions are not in working order!
* remove the ex?? folders
* run makehandson on all *solution folders (omitting any that don't
	require a base folder, such as multiple "bonus" solutions)
* run _mvn compile_ in the ex?? folders
* refresh the Eclipse projects (using a separate 
* Undeploy server artifacts (if running tests deployed any)
* Generate a timestamp file "about.html"

You can see the full (possibly overblown) version of this automation, and my overall setup, in
the _scripts_ folder of
https://github.com/IanDarwin/CourseFiles936[the github repo for my Course 936].

Final note: have the discipline to *do not make any manual changes* after running
your script, thinking you'll fix them "tomorrow." That "tomorrow" never comes.
Fix the solution, and at least re-run _makehandson_ with that solution folder.
The course grades you save may be your own!

=== Learning Tree Specifics

Learning Tree authors are urged to use the name _CourseFilesNNNN_ for the root
of your workspace, _sourcecode_ for both exercises and downows, and the naming convention

	exNN/exNNSolution name for exercises;
	donowNN/donowNNSolution name for short do-now projects.

Doing this consistently makes it _much_ easier when combining work from multiple
courses into a custom course load!

== Rebuilding the Program

The source file for makehandson is an Eclipse project. Open it in Eclipse
and make any changes.

Or, using Maven, just do _mvn package_

== Bugs/ToDos

See the file TODO.adoc

== Modifying the Program

Well, this is Github, so just fork it and hack away. If you make it better,
send me a note and/or a pull request.

Enjoy.

Ian Darwin
ian@darwinsys.com
