#!/bin/sh

# Make the Hands-Ons from the Solutions, which are "known" to work.

# set -x

# The possibility of portability.
case $(UNAME) in
	cyg*|CYG*)	# Alas, specific to our setup.
		HOME='C:/Users/student';;
esac

JAR=${HOME}/.m2/repository/com/darwinsys/makehandsons/1.0-SNAPSHOT/makehandsons-1.0-SNAPSHOT.jar

if [ ! -f ${JAR} ]; then
	echo "Jar not found, install ${JAR} using 'mvn install' in makehandson source" >&2
	exit 1
fi

java -jar ${JAR} ${*-*solution}
