#!/bin/sh

# Make the Hands-Ons from the Solutions, which are "known" to work.

# set -x

# The possibility of portability.
JAR=${HOME}/lib/makehandsons.jar

if [ ! -f ${JAR} ]; then
	echo "Jar not found, install ${JAR} using 'mvn install' in makehandson source" >&2
	exit 1
fi

java -jar ${JAR} ${*}
